In [2]:
import pandas as pd

df = pd.read_csv('dataset.csv')

In [3]:
df.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
set = {}

In [24]:
def process(d: str):
    d = d.capitalize
    return d

In [25]:
for d in df['Disease']:
    set[process(d)] = True

In [21]:
with open('file.txt', 'r+') as file:
    file.write(str(set.keys()))

In [4]:
def process(s):
    s = s.strip()
    s = s.replace("_", " ")
    s = s.replace("  ", " ")
    return s

In [5]:
symptoms = set()


for col in df.columns:
    if col == 'Disease':
        continue

    for s in df[col]:
        if type(s)==float:
            continue

        s = process(s)
        symptoms.add(s)

In [7]:
print(symptoms.__str__())

{'swelling joints', 'ulcers on tongue', 'congestion', 'altered sensorium', 'blurred and distorted vision', 'high fever', 'painful walking', 'irritability', 'receiving unsterile injections', 'anxiety', 'rusty sputum', 'increased appetite', 'mood swings', 'weakness of one body side', 'hip joint pain', 'passage of gases', 'weight gain', 'distention of abdomen', 'internal itching', 'skin peeling', 'continuous sneezing', 'swelled lymph nodes', 'puffy face and eyes', 'swollen legs', 'acute liver failure', 'extra marital contacts', 'bloody stool', 'receiving blood transfusion', 'history of alcohol consumption', 'watering from eyes', 'brittle nails', 'irregular sugar level', 'red sore around nose', 'polyuria', 'obesity', 'malaise', 'scurring', 'restlessness', 'inflammatory nails', 'silver like dusting', 'nodal skin eruptions', 'pain in anal region', 'small dents in nails', 'constipation', 'indigestion', 'headache', 'muscle pain', 'nausea', 'prominent veins on calf', 'itching', 'lack of concentration', 'red spots over body', 'patches in throat', 'blackheads', 'dischromic patches', 'stomach pain', 'knee pain', 'muscle weakness', 'cold hands and feets', 'fatigue', 'yellowish skin', 'palpitations', 'bruising', 'fast heart rate', 'cough', 'cramps', 'drying and tingling lips', 'pain during bowel movements', 'swollen extremeties', 'continuous feel of urine', 'excessive hunger', 'loss of smell', 'stiff neck', 'diarrhoea', 'irritation in anus', 'weakness in limbs', 'blood in sputum', 'shivering', 'dark urine', 'bladder discomfort', 'swollen blood vessels', 'depression', 'yellow crust ooze', 'vomiting', 'back pain', 'lethargy', 'yellow urine', 'enlarged thyroid', 'dizziness', 'slurred speech', 'muscle wasting', 'weight loss', 'stomach bleeding', 'neck pain', 'loss of balance', 'spinning movements', 'chest pain', 'toxic look (typhos)', 'chills', 'unsteadiness', 'blister', 'loss of appetite', 'foul smell of urine', 'fluid overload', 'coma', 'breathlessness', 'pus filled pimples', 'family history', 'pain behind the eyes', 'burning micturition', 'sinus pressure', 'joint pain', 'mild fever', 'redness of eyes', 'phlegm', 'dehydration', 'spotting urination', 'abdominal pain', 'abnormal menstruation', 'skin rash', 'movement stiffness', 'belly pain', 'visual disturbances', 'runny nose', 'throat irritation', 'sunken eyes', 'mucoid sputum', 'acidity', 'swelling of stomach', 'sweating', 'yellowing of eyes'}

In [22]:
len(symptoms)

131

In [25]:
mapds = {}
col = []

for _ in range(4920):
    col.append(0)

for s in symptoms: 
    # print(s)
    s = process(s)
    mapds[s] = col.copy()
    # print(mapds[s])

print(mapds.keys())

mapds['Diagnosis'] = []

# print(mapds)

dict_keys(['swelling joints', 'ulcers on tongue', 'congestion', 'altered sensorium', 'blurred and distorted vision', 'high fever', 'painful walking', 'irritability', 'receiving unsterile injections', 'anxiety', 'rusty sputum', 'increased appetite', 'mood swings', 'weakness of one body side', 'hip joint pain', 'passage of gases', 'weight gain', 'distention of abdomen', 'internal itching', 'skin peeling', 'continuous sneezing', 'swelled lymph nodes', 'puffy face and eyes', 'swollen legs', 'acute liver failure', 'extra marital contacts', 'bloody stool', 'receiving blood transfusion', 'history of alcohol consumption', 'watering from eyes', 'brittle nails', 'irregular sugar level', 'red sore around nose', 'polyuria', 'obesity', 'malaise', 'scurring', 'restlessness', 'inflammatory nails', 'silver like dusting', 'nodal skin eruptions', 'pain in anal region', 'small dents in nails', 'constipation', 'indigestion', 'headache', 'muscle pain', 'nausea', 'prominent veins on calf', 'itching', 'lack of concentration', 'red spots over body', 'patches in throat', 'blackheads', 'dischromic patches', 'stomach pain', 'knee pain', 'muscle weakness', 'cold hands and feets', 'fatigue', 'yellowish skin', 'palpitations', 'bruising', 'fast heart rate', 'cough', 'cramps', 'drying and tingling lips', 'pain during bowel movements', 'swollen extremeties', 'continuous feel of urine', 'excessive hunger', 'loss of smell', 'stiff neck', 'diarrhoea', 'irritation in anus', 'weakness in limbs', 'blood in sputum', 'shivering', 'dark urine', 'bladder discomfort', 'swollen blood vessels', 'depression', 'yellow crust ooze', 'vomiting', 'back pain', 'lethargy', 'yellow urine', 'enlarged thyroid', 'dizziness', 'slurred speech', 'muscle wasting', 'weight loss', 'stomach bleeding', 'neck pain', 'loss of balance', 'spinning movements', 'chest pain', 'toxic look (typhos)', 'chills', 'unsteadiness', 'blister', 'loss of appetite', 'foul smell of urine', 'fluid overload', 'coma', 'breathlessness', 'pus filled pimples', 'family history', 'pain behind the eyes', 'burning micturition', 'sinus pressure', 'joint pain', 'mild fever', 'redness of eyes', 'phlegm', 'dehydration', 'spotting urination', 'abdominal pain', 'abnormal menstruation', 'skin rash', 'movement stiffness', 'belly pain', 'visual disturbances', 'runny nose', 'throat irritation', 'sunken eyes', 'mucoid sputum', 'acidity', 'swelling of stomach', 'sweating', 'yellowing of eyes'])

In [17]:
keys = []
for s in symptoms:
    keys.append(s)
print(keys)

with open('file.txt', 'r+') as file:
    file.write(keys.__str__())

['swelling joints', 'ulcers on tongue', 'congestion', 'altered sensorium', 'blurred and distorted vision', 'high fever', 'painful walking', 'irritability', 'receiving unsterile injections', 'anxiety', 'rusty sputum', 'increased appetite', 'mood swings', 'weakness of one body side', 'hip joint pain', 'passage of gases', 'weight gain', 'distention of abdomen', 'internal itching', 'skin peeling', 'continuous sneezing', 'swelled lymph nodes', 'puffy face and eyes', 'swollen legs', 'acute liver failure', 'extra marital contacts', 'bloody stool', 'receiving blood transfusion', 'history of alcohol consumption', 'watering from eyes', 'brittle nails', 'irregular sugar level', 'red sore around nose', 'polyuria', 'obesity', 'malaise', 'scurring', 'restlessness', 'inflammatory nails', 'silver like dusting', 'nodal skin eruptions', 'pain in anal region', 'small dents in nails', 'constipation', 'indigestion', 'headache', 'muscle pain', 'nausea', 'prominent veins on calf', 'itching', 'lack of concentration', 'red spots over body', 'patches in throat', 'blackheads', 'dischromic patches', 'stomach pain', 'knee pain', 'muscle weakness', 'cold hands and feets', 'fatigue', 'yellowish skin', 'palpitations', 'bruising', 'fast heart rate', 'cough', 'cramps', 'drying and tingling lips', 'pain during bowel movements', 'swollen extremeties', 'continuous feel of urine', 'excessive hunger', 'loss of smell', 'stiff neck', 'diarrhoea', 'irritation in anus', 'weakness in limbs', 'blood in sputum', 'shivering', 'dark urine', 'bladder discomfort', 'swollen blood vessels', 'depression', 'yellow crust ooze', 'vomiting', 'back pain', 'lethargy', 'yellow urine', 'enlarged thyroid', 'dizziness', 'slurred speech', 'muscle wasting', 'weight loss', 'stomach bleeding', 'neck pain', 'loss of balance', 'spinning movements', 'chest pain', 'toxic look (typhos)', 'chills', 'unsteadiness', 'blister', 'loss of appetite', 'foul smell of urine', 'fluid overload', 'coma', 'breathlessness', 'pus filled pimples', 'family history', 'pain behind the eyes', 'burning micturition', 'sinus pressure', 'joint pain', 'mild fever', 'redness of eyes', 'phlegm', 'dehydration', 'spotting urination', 'abdominal pain', 'abnormal menstruation', 'skin rash', 'movement stiffness', 'belly pain', 'visual disturbances', 'runny nose', 'throat irritation', 'sunken eyes', 'mucoid sputum', 'acidity', 'swelling of stomach', 'sweating', 'yellowing of eyes']

In [26]:
index = 0
for row in df.iterrows():
    for col in df.columns:
        if col=='Disease' or type(row[1][col])==float:
            continue            
        s = process(row[1][col])
        # print(row[1][col])
        mapds[s][index]=1
    mapds['Diagnosis'].append(row[1]['Disease'])
    index+=1

In [27]:
mapds['Diagnosis']

['Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 ...]

In [28]:
y = mapds['Diagnosis']
x = mapds

In [29]:
newds = pd.DataFrame(mapds)
# newds.la
y_train = newds['Diagnosis'][0:4000]
xs = []
for s in symptoms:
    xs.append(s)
x_train = newds[xs][0:4000]

y_test = newds['Diagnosis'][4001:-1]
x_test = newds[xs][4001:-1]

In [30]:
x_train.head()

,swelling joints,ulcers on tongue,congestion,altered sensorium,blurred and distorted vision,high fever,painful walking,irritability,receiving unsterile injections,anxiety,...,belly pain,visual disturbances,runny nose,throat irritation,sunken eyes,mucoid sputum,acidity,swelling of stomach,sweating,yellowing of eyes
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
y

['Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'Typhoid',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'hepatitis A',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis B',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis C',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis D',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Hepatitis E',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Alcoholic hepatitis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Tuberculosis',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Common Cold',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Pneumonia',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Dimorphic hemmorhoids(piles)',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Heart attack',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Varicose veins',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hypothyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hyperthyroidism',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Hypoglycemia',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Osteoarthristis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 'Arthritis',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 '(vertigo) Paroymsal  Positional Vertigo',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Urinary tract infection',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Psoriasis',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Impetigo',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'AIDS',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Diabetes ',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Gastroenteritis',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Bronchial Asthma',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Hypertension ',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Migraine',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Cervical spondylosis',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Paralysis (brain hemorrhage)',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Jaundice',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Malaria',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Chicken pox',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 'Dengue',
 ...]

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
model = LogisticRegression()

In [34]:
model.fit(x_train, y_train)

LogisticRegression()

In [35]:
y_pred = model.predict(x_test)

In [36]:
from sklearn.metrics import accuracy_score

In [37]:
acc = accuracy_score(y_test, y_pred)

In [38]:
acc

1.0

In [39]:
y_train_pred = model.predict(x_train)
acc_train = accuracy_score(y_train, y_train_pred)

In [40]:
acc_train

1.0

In [ ]:
# model.save('/symptoms/symptomsbased_model.pkl')

In [52]:
import pickle

filename = 'symptomsbased_model.pkl'
# Load the model from disk
with open(filename, 'wb') as file:
    pickle.dump(model, file)

In [ ]:
# loaded_model.predict(x_test)

NameError: name 'x_test' is not defined