In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("akshaydattatraykhare/diabetes-dataset")

print("Path to dataset files:", path)

c:\Users\YashMehta\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Warning: Looks like you're using an outdated `kagglehub` version, please consider updating (latest version: 0.3.11)
Downloading from https://www.kaggle.com/api/v1/datasets/download/akshaydattatraykhare/diabetes-dataset?dataset_version_number=1...

100%|██████████| 8.91k/8.91k [00:00<00:00, 4.55MB/s]

Extracting files...
Path to dataset files: C:\Users\YashMehta\.cache\kagglehub\datasets\akshaydattatraykhare\diabetes-dataset\versions\1

In [16]:
import os

os.listdir(path)

import pandas as pd

import numpy as np

df = pd.read_csv(path+'/diabetes.csv')

In [4]:
df.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [17]:
min = {}
max = {}

for col in df.columns:
    max[col] = df[col].max()
    min[col] = df[col].min()

In [24]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [21]:
newdf = {}

for col in df.columns:
    newdf[col] = []

In [22]:
for row in df.iterrows():
    for col in df.columns:
        row[1][col] = (max[col] - row[1][col])/(max[col]-min[col])
        newdf[col].append(row[1][col])
    # print(row)

    # break

In [23]:
newdf

{'Pregnancies': [np.float64(0.6470588235294118),
  np.float64(0.9411764705882353),
  np.float64(0.5294117647058824),
  np.float64(0.9411764705882353),
  np.float64(1.0),
  np.float64(0.7058823529411765),
  np.float64(0.8235294117647058),
  np.float64(0.4117647058823529),
  np.float64(0.8823529411764706),
  np.float64(0.5294117647058824),
  np.float64(0.7647058823529411),
  np.float64(0.4117647058823529),
  np.float64(0.4117647058823529),
  np.float64(0.9411764705882353),
  np.float64(0.7058823529411765),
  np.float64(0.5882352941176471),
  np.float64(1.0),
  np.float64(0.5882352941176471),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(0.8235294117647058),
  np.float64(0.5294117647058824),
  np.float64(0.5882352941176471),
  np.float64(0.47058823529411764),
  np.float64(0.35294117647058826),
  np.float64(0.4117647058823529),
  np.float64(0.5882352941176471),
  np.float64(0.9411764705882353),
  np.float64(0.23529411764705882),
  np.float64(0.7058823529411765),
  np.float64(0.7058823529411765),
  np.float64(0.8235294117647058),
  np.float64(0.8235294117647058),
  np.float64(0.6470588235294118),
  np.float64(0.4117647058823529),
  np.float64(0.7647058823529411),
  np.float64(0.35294117647058826),
  np.float64(0.47058823529411764),
  np.float64(0.8823529411764706),
  np.float64(0.7647058823529411),
  np.float64(0.8235294117647058),
  np.float64(0.5882352941176471),
  np.float64(0.5882352941176471),
  np.float64(0.47058823529411764),
  np.float64(0.5882352941176471),
  np.float64(1.0),
  np.float64(0.9411764705882353),
  np.float64(0.8823529411764706),
  np.float64(0.5882352941176471),
  np.float64(0.5882352941176471),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(0.7058823529411765),
  np.float64(0.5294117647058824),
  np.float64(0.5882352941176471),
  np.float64(0.9411764705882353),
  np.float64(0.5882352941176471),
  np.float64(1.0),
  np.float64(1.0),
  np.float64(1.0),
  np.float64(0.8823529411764706),
  np.float64(0.5294117647058824),
  np.float64(0.7058823529411765),
  np.float64(0.8823529411764706),
  np.float64(0.5882352941176471),
  np.float64(0.7058823529411765),
  np.float64(1.0),
  np.float64(0.8823529411764706),
  np.float64(0.9411764705882353),
  np.float64(0.7647058823529411),
  np.float64(0.8823529411764706),
  np.float64(0.7058823529411765),
  np.float64(0.23529411764705882),
  np.float64(0.7647058823529411),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(0.5882352941176471),
  np.float64(0.7058823529411765),
  np.float64(1.0),
  np.float64(0.8823529411764706),
  np.float64(0.8235294117647058),
  np.float64(0.8823529411764706),
  np.float64(0.5882352941176471),
  np.float64(1.0),
  np.float64(0.7058823529411765),
  np.float64(0.8823529411764706),
  np.float64(0.23529411764705882),
  np.float64(0.8823529411764706),
  np.float64(0.11764705882352941),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(0.7647058823529411),
  np.float64(0.5882352941176471),
  np.float64(0.7647058823529411),
  np.float64(0.8823529411764706),
  np.float64(0.6470588235294118),
  np.float64(0.8823529411764706),
  np.float64(0.9411764705882353),
  np.float64(0.6470588235294118),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(1.0),
  np.float64(0.9411764705882353),
  np.float64(0.8823529411764706),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(0.7647058823529411),
  np.float64(0.8235294117647058),
  np.float64(1.0),
  np.float64(0.8235294117647058),
  np.float64(0.5294117647058824),
  np.float64(0.9411764705882353),
  np.float64(0.7647058823529411),
  np.float64(0.5882352941176471),
  np.float64(0.7647058823529411),
  np.float64(0.7058823529411765),
  np.float64(0.7058823529411765),
  np.float64(0.7647058823529411),
  np.float64(0.7647058823529411),
  np.float64(1.0),
  np.float64(0.6470588235294118),
  np.float64(0.8823529411764706),
  np.float64(0.7058823529411765),
  np.float64(1.0),
  np.float64(0.9411764705882353),
  np.float64(0.8235294117647058),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(1.0),
  np.float64(0.7647058823529411),
  np.float64(0.47058823529411764),
  np.float64(0.8235294117647058),
  np.float64(0.5294117647058824),
  np.float64(0.8823529411764706),
  np.float64(0.8823529411764706),
  np.float64(1.0),
  np.float64(1.0),
  np.float64(1.0),
  np.float64(0.7058823529411765),
  np.float64(0.8235294117647058),
  np.float64(0.7058823529411765),
  np.float64(0.8823529411764706),
  np.float64(0.4117647058823529),
  np.float64(0.7647058823529411),
  np.float64(1.0),
  np.float64(0.47058823529411764),
  np.float64(0.8823529411764706),
  np.float64(0.7058823529411765),
  np.float64(0.8823529411764706),
  np.float64(0.9411764705882353),
  np.float64(0.7647058823529411),
  np.float64(0.47058823529411764),
  np.float64(0.9411764705882353),
  np.float64(0.5294117647058824),
  np.float64(0.5882352941176471),
  np.float64(0.8823529411764706),
  np.float64(0.9411764705882353),
  np.float64(0.8823529411764706),
  np.float64(0.0),
  np.float64(0.7647058823529411),
  np.float64(0.5882352941176471),
  np.float64(1.0),
  np.float64(0.8823529411764706),
  np.float64(1.0),
  np.float64(0.6470588235294118),
  np.float64(0.8235294117647058),
  np.float64(0.7647058823529411),
  np.float64(0.7647058823529411),
  np.float64(0.8235294117647058),
  np.float64(0.6470588235294118),
  np.float64(0.6470588235294118),
  np.float64(0.8823529411764706),
  np.float64(0.9411764705882353),
  np.float64(0.8823529411764706),
  np.float64(0.5294117647058824),
  np.float64(0.6470588235294118),
  np.float64(1.0),
  np.float64(0.7058823529411765),
  np.float64(0.7058823529411765),
  np.float64(0.6470588235294118),
  np.float64(1.0),
  np.float64(0.9411764705882353),
  np.float64(0.7058823529411765),
  np.float64(0.7647058823529411),
  np.float64(0.5882352941176471),
  np.float64(0.5294117647058824),
  np.float64(0.9411764705882353),
  np.float64(0.5294117647058824),
  np.float64(0.7058823529411765),
  np.float64(0.8235294117647058),
  np.float64(0.47058823529411764),
  np.float64(0.5882352941176471),
  np.float64(0.35294117647058826),
  np.float64(0.5294117647058824),
  np.float64(0.7058823529411765),
  np.float64(0.9411764705882353),
  np.float64(0.8235294117647058),
  np.float64(0.7647058823529411),
  np.float64(0.7647058823529411),
  np.float64(1.0),
  np.float64(0.9411764705882353),
  np.float64(1.0),
  np.float64(0.8823529411764706),
  np.float64(0.6470588235294118),
  np.float64(0.7058823529411765),
  np.float64(0.5294117647058824),
  np.float64(0.7058823529411765),
  np.float64(0.9411764705882353),
  np.float64(0.5882352941176471),
  np.float64(0.8823529411764706),
  np.float64(1.0),
  np.float64(0.5882352941176471),
  np.float64(1.0),
  np.float64(0.47058823529411764),
  np.float64(0.29411764705882354),
  np.float64(0.7058823529411765),
  np.float64(0.6470588235294118),
  np.float64(0.7058823529411765),
  np.float64(0.7058823529411765),
  np.float64(1.0),
  np.float64(0.8823529411764706),
  np.float64(0.5882352941176471),
  np.float64(0.5882352941176471),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(1.0),
  np.float64(0.8235294117647058),
  np.float64(0.7647058823529411),
  np.float64(1.0),
  np.float64(0.7647058823529411),
  np.float64(0.6470588235294118),
  np.float64(0.9411764705882353),
  np.float64(0.7647058823529411),
  np.float64(0.8235294117647058),
  np.float64(0.7647058823529411),
  np.float64(0.5882352941176471),
  np.float64(1.0),
  np.float64(0.47058823529411764),
  np.float64(1.0),
  np.float64(0.9411764705882353),
  np.float64(0.7647058823529411),
  np.float64(0.8235294117647058),
  np.float64(0.6470588235294118),
  np.float64(0.8823529411764706),
  np.float64(0.47058823529411764),
  np.float64(0.4117647058823529),
  np.float64(1.0),
  np.float64(0.47058823529411764),
  np.float64(0.9411764705882353),
  np.float64(0.47058823529411764),
  np.float64(0.8823529411764706),
  np.float64(0.8823529411764706),
  np.float64(1.0),
  np.float64(0.29411764705882354),
  np.float64(0.9411764705882353),
  np.float64(0.8235294117647058),
  np.float64(0.8823529411764706),
  np.float64(0.9411764705882353),
  np.float64(0.35294117647058826),
  np.float64(0.8235294117647058),
  np.float64(0.8235294117647058),
  np.float64(0.7647058823529411),
  np.float64(0.8235294117647058),
  np.float64(0.7647058823529411),
  np.float64(0.7058823529411765),
  np.float64(1.0),
  np.float64(0.8823529411764706),
  np.float64(1.0),
  np.float64(0.8823529411764706),
  np.float64(0.4117647058823529),
  np.float64(0.8823529411764706),
  np.float64(0.8235294117647058),
  np.float64(0.9411764705882353),
  np.float64(0.23529411764705882),
  np.float64(0.8823529411764706),
  np.float64(0.5882352941176471),
  np.float64(1.0),
  np.float64(0.7058823529411765),
  np.float64(0.8823529411764706),
  np.float64(1.0),
  np.float64(0.4117647058823529),
  np.float64(0.5882352941176471),
  np.float64(0.5882352941176471),
  np.float64(0.8823529411764706),
  np.float64(0.5882352941176471),
  np.float64(0.7058823529411765),
  np.float64(0.9411764705882353),
  np.float64(0.7647058823529411),
  np.float64(0.7058823529411765),
  np.float64(1.0),
  np.float64(1.0),
  np.float64(0.8823529411764706),
  np.float64(0.9411764705882353),
  np.float64(1.0),
  np.float64(0.6470588235294118),
  np.float64(0.8823529411764706),
  np.float64(1.0),
  np.float64(0.17647058823529413),
  np.float64(0.5294117647058824),
  np.float64(1.0),
  np.float64(0.8823529411764706),
  np.float64(0.7058823529411765),
  np.float64(0.7058823529411765),
  np.float64(0.8235294117647058),
  np.float64(0.8823529411764706),
  np.float64(0.4117647058823529),
  np.float64(1.0),
  np.float64(1.0),
  np.float64(0.8823529411764706),
  np.float64(0.6470588235294118),
  np.float64(1.0),
  np.float64(0.8823529411764706),
  np.float64(0.8235294117647058),
  np.float64(0.5882352941176471),
  np.float64(0.8823529411764706),
  np.float64(0.8235294117647058),
  np.float64(0.8235294117647058),
  np.float64(0.8235294117647058),
  np.float64(0.6470588235294118),
  np.float64(0.7647058823529411),
  np.float64(0.8235294117647058),
  np.float64(1.0),
  np.float64(0.23529411764705882),
  np.float64(0.8823529411764706),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(0.4117647058823529),
  np.float64(0.8823529411764706),
  np.float64(0.6470588235294118),
  np.float64(0.5294117647058824),
  np.float64(0.8823529411764706),
  np.float64(0.9411764705882353),
  np.float64(0.29411764705882354),
  np.float64(0.9411764705882353),
  np.float64(1.0),
  np.float64(1.0),
  np.float64(0.7058823529411765),
  np.float64(0.47058823529411764),
  np.float64(0.5882352941176471),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(0.7058823529411765),
  np.float64(0.5294117647058824),
  np.float64(0.5294117647058824),
  np.float64(0.9411764705882353),
  np.float64(0.8235294117647058),
  np.float64(0.8235294117647058),
  np.float64(0.7058823529411765),
  np.float64(0.7647058823529411),
  np.float64(0.7647058823529411),
  np.float64(0.8235294117647058),
  np.float64(0.9411764705882353),
  np.float64(0.8235294117647058),
  np.float64(0.47058823529411764),
  np.float64(0.9411764705882353),
  np.float64(0.23529411764705882),
  np.float64(0.29411764705882354),
  np.float64(0.9411764705882353),
  np.float64(0.7058823529411765),
  np.float64(0.7058823529411765),
  np.float64(0.7058823529411765),
  np.float64(0.7647058823529411),
  np.float64(0.7647058823529411),
  np.float64(0.7058823529411765),
  np.float64(0.6470588235294118),
  np.float64(1.0),
  np.float64(0.8235294117647058),
  np.float64(0.9411764705882353),
  np.float64(0.8235294117647058),
  np.float64(1.0),
  np.float64(1.0),
  np.float64(0.8823529411764706),
  np.float64(0.8823529411764706),
  np.float64(0.29411764705882354),
  np.float64(1.0),
  np.float64(0.9411764705882353),
  np.float64(0.7647058823529411),
  np.float64(1.0),
  np.float64(0.9411764705882353),
  np.float64(1.0),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(0.7058823529411765),
  np.float64(0.5294117647058824),
  np.float64(0.7058823529411765),
  np.float64(0.8235294117647058),
  np.float64(0.9411764705882353),
  np.float64(0.7058823529411765),
  np.float64(0.9411764705882353),
  np.float64(0.7647058823529411),
  np.float64(0.7647058823529411),
  np.float64(0.8823529411764706),
  np.float64(0.8235294117647058),
  np.float64(1.0),
  np.float64(0.8235294117647058),
  np.float64(0.8235294117647058),
  np.float64(0.7647058823529411),
  np.float64(0.6470588235294118),
  np.float64(0.7058823529411765),
  np.float64(0.47058823529411764),
  np.float64(0.7058823529411765),
  np.float64(0.8823529411764706),
  np.float64(0.7647058823529411),
  np.float64(1.0),
  np.float64(0.5294117647058824),
  np.float64(0.9411764705882353),
  np.float64(0.6470588235294118),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(1.0),
  np.float64(0.8235294117647058),
  np.float64(0.9411764705882353),
  np.float64(0.7647058823529411),
  np.float64(0.9411764705882353),
  np.float64(0.8235294117647058),
  np.float64(0.9411764705882353),
  np.float64(0.8823529411764706),
  np.float64(1.0),
  np.float64(0.8823529411764706),
  np.float64(0.5294117647058824),
  np.float64(0.7647058823529411),
  np.float64(1.0),
  np.float64(0.9411764705882353),
  np.float64(1.0),
  np.float64(0.9411764705882353),
  np.float64(0.8823529411764706),
  np.float64(0.8235294117647058),
  np.float64(0.9411764705882353),
  np.float64(0.8823529411764706),
  np.float64(0.9411764705882353),
  np.float64(1.0),
  np.float64(0.29411764705882354),
  np.float64(0.7058823529411765),
  np.float64(0.9411764705882353),
  np.float64(0.6470588235294118),
  np.float64(1.0),
  np.float64(0.8823529411764706),
  np.float64(0.7647058823529411),
  np.float64(0.5294117647058824),
  np.float64(0.7647058823529411),
  np.float64(1.0),
  np.float64(0.9411764705882353),
  np.float64(1.0),
  np.float64(1.0),
  np.float64(1.0),
  np.float64(0.9411764705882353),
  np.float64(0.8823529411764706),
  np.float64(1.0),
  np.float64(0.8823529411764706),
  np.float64(0.8823529411764706),
  np.float64(0.17647058823529413),
  np.float64(0.9411764705882353),
  np.float64(0.7058823529411765),
  np.float64(0.4117647058823529),
  np.float64(0.47058823529411764),
  np.float64(0.47058823529411764),
  np.float64(0.9411764705882353),
  np.float64(0.5294117647058824),
  np.float64(0.7058823529411765),
  np.float64(0.4117647058823529),
  np.float64(1.0),
  np.float64(1.0),
  np.float64(1.0),
  np.float64(0.5294117647058824),
  np.float64(0.6470588235294118),
  np.float64(0.9411764705882353),
  np.float64(1.0),
  np.float64(1.0),
  np.float64(0.5882352941176471),
  np.float64(0.7647058823529411),
  np.float64(1.0),
  np.float64(0.8823529411764706),
  np.float64(0.5882352941176471),
  np.float64(0.5294117647058824),
  np.float64(0.7647058823529411),
  np.float64(0.8235294117647058),
  np.float64(1.0),
  np.float64(0.7647058823529411),
  np.float64(1.0),
  np.float64(1.0),
  np.float64(1.0),
  np.float64(0.9411764705882353),
  np.float64(1.0),
  np.float64(0.7647058823529411),
  np.float64(0.5294117647058824),
  np.float64(0.8823529411764706),
  np.float64(0.8823529411764706),
  np.float64(0.7647058823529411),
  np.float64(0.7647058823529411),
  np.float64(0.8235294117647058),
  np.float64(0.6470588235294118),
  np.float64(0.7058823529411765),
  np.float64(0.8823529411764706),
  np.float64(0.5882352941176471),
  np.float64(0.6470588235294118),
  np.float64(0.8823529411764706),
  np.float64(0.8235294117647058),
  np.float64(0.6470588235294118),
  np.float64(0.5882352941176471),
  np.float64(0.8235294117647058),
  np.float64(0.4117647058823529),
  np.float64(1.0),
  np.float64(0.9411764705882353),
  np.float64(0.8823529411764706),
  np.float64(0.5294117647058824),
  np.float64(0.29411764705882354),
  np.float64(1.0),
  np.float64(0.47058823529411764),
  np.float64(0.8823529411764706),
  np.float64(0.8235294117647058),
  np.float64(0.8235294117647058),
  np.float64(0.47058823529411764),
  np.float64(0.5882352941176471),
  np.float64(0.23529411764705882),
  np.float64(0.6470588235294118),
  np.float64(0.8823529411764706),
  np.float64(0.8235294117647058),
  np.float64(0.6470588235294118),
  np.float64(0.47058823529411764),
  np.float64(0.8235294117647058),
  np.float64(0.8235294117647058),
  np.float64(0.9411764705882353),
  np.float64(0.8235294117647058),
  np.float64(1.0),
  np.float64(1.0),
  np.float64(0.8823529411764706),
  np.float64(1.0),
  np.float64(0.9411764705882353),
  np.float64(0.6470588235294118),
  np.float64(0.9411764705882353),
  np.float64(0.7647058823529411),
  np.float64(1.0),
  np.float64(1.0),
  np.float64(1.0),
  np.float64(0.8235294117647058),
  np.float64(0.5294117647058824),
  np.float64(0.8235294117647058),
  np.float64(0.4117647058823529),
  np.float64(0.7647058823529411),
  np.float64(0.9411764705882353),
  np.float64(0.5294117647058824),
  np.float64(0.7058823529411765),
  np.float64(0.7647058823529411),
  np.float64(0.9411764705882353),
  np.float64(0.7647058823529411),
  np.float64(0.9411764705882353),
  np.float64(0.8235294117647058),
  np.float64(0.6470588235294118),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(0.5882352941176471),
  np.float64(0.9411764705882353),
  np.float64(0.5294117647058824),
  np.float64(0.35294117647058826),
  np.float64(0.35294117647058826),
  np.float64(0.6470588235294118),
  np.float64(1.0),
  np.float64(0.9411764705882353),
  np.float64(0.6470588235294118),
  np.float64(1.0),
  np.float64(0.8823529411764706),
  np.float64(0.9411764705882353),
  np.float64(0.6470588235294118),
  np.float64(0.7647058823529411),
  np.float64(1.0),
  np.float64(0.8235294117647058),
  np.float64(0.8823529411764706),
  np.float64(0.8235294117647058),
  np.float64(0.8823529411764706),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(0.6470588235294118),
  np.float64(0.8823529411764706),
  np.float64(0.4117647058823529),
  np.float64(0.8823529411764706),
  np.float64(1.0),
  np.float64(0.6470588235294118),
  np.float64(0.29411764705882354),
  np.float64(0.5294117647058824),
  np.float64(0.5294117647058824),
  np.float64(0.9411764705882353),
  np.float64(0.5294117647058824),
  np.float64(0.6470588235294118),
  np.float64(0.8235294117647058),
  np.float64(1.0),
  np.float64(0.35294117647058826),
  np.float64(0.8823529411764706),
  np.float64(0.8235294117647058),
  np.float64(0.8823529411764706),
  np.float64(0.6470588235294118),
  np.float64(1.0),
  np.float64(1.0),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(0.6470588235294118),
  np.float64(0.9411764705882353),
  np.float64(0.5882352941176471),
  np.float64(0.7647058823529411),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(0.9411764705882353),
  np.float64(1.0),
  np.float64(0.9411764705882353),
  np.float64(0.8235294117647058),
  np.float64(0.8235294117647058),
  np.float64(0.5882352941176471),
  np.float64(0.6470588235294118),
  np.float64(0.35294117647058826),
  np.float64(0.8235294117647058),
  np.float64(0.6470588235294118),
  np.float64(0.8823529411764706),
  np.float64(0.47058823529411764),
  np.float64(1.0),
  np.float64(0.8823529411764706),
  np.float64(0.8823529411764706),
  np.float64(0.6470588235294118),
  np.float64(1.0),
  np.float64(0.8823529411764706),
  np.float64(0.7647058823529411),
  np.float64(1.0),
  np.float64(1.0),
  np.float64(0.7058823529411765),
  np.float64(0.7647058823529411),

In [25]:
newds = pd.DataFrame(newdf)

In [27]:
newds.head()

   Pregnancies   Glucose  ...       Age  Outcome
0     0.647059  0.256281  ...  0.516667      0.0
1     0.941176  0.572864  ...  0.833333      1.0
2     0.529412  0.080402  ...  0.816667      0.0
3     0.941176  0.552764  ...  1.000000      1.0
4     1.000000  0.311558  ...  0.800000      0.0

[5 rows x 9 columns]

In [30]:
len(newds)

768

In [31]:
x_train = newds[0:int(len(newds)*0.9)]
x_test = newds[int(len(newds)*0.9):-1]

In [32]:
x_train.head()

   Pregnancies   Glucose  ...       Age  Outcome
0     0.647059  0.256281  ...  0.516667      0.0
1     0.941176  0.572864  ...  0.833333      1.0
2     0.529412  0.080402  ...  0.816667      0.0
3     0.941176  0.552764  ...  1.000000      1.0
4     1.000000  0.311558  ...  0.800000      0.0

[5 rows x 9 columns]

In [44]:
from sklearn.linear_model import LogisticRegression

X = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age']
y = ['Outcome']

model = LogisticRegression()

model.fit(x_train[X], x_train[y])

c:\Users\YashMehta\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [45]:
pred = model.predict(x_test[X])

In [46]:
from sklearn.metrics import accuracy_score

print(accuracy_score(pred, x_test[y]))

0.8026315789473685

In [ ]:
import pickle

filename = 'diabetes_model.pkl'
# Load the model from disk
with open(filename, 'wb') as file:
    pickle.dump(model, file)